#!/bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

xrandr --output HDMI-1-0 --auto --left-of eDP1 --primary --mode 1920x1080 --rate 144 --output eDP1 --noprimary --mode 1920x1080 --rate 60 &

# keybindings daemon
sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &

# diversity of apps to start
# knm-applet &
volumeicon &

# Boot picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/leftwm/themes/current/picom.conf &> /dev/null &
fi

# Set the theme.toml config
# echo "LoadTheme $SCRIPTPATH/theme.ron" > $XDG_RUNTIME_DIR/leftwm/commands-0.pipe
leftwm command "LoadTheme $SCRIPTPATH/theme.ron" 

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH"/background.jpg
fi


index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  let index=index+1
done

